branches:
  only:
    - master
    - semantic-release-integration

jobs:
  include:
    - stage: release
      node_js: lts/*
      install:
        - travis_retry npm install
      script:
        - npm run semantic-release