branches:
  only:
    - master

jobs:
  include:
    - stage: release
      node_js: lts/*
      install:
        - travis_retry npm install
      before-script:
        - npm prune
      script:
        - npm run test
      after-success:
        - npm run semantic-release
        - bash <(curl -s https://codecov.io/bash)